### ISSUE TITLE
Please move from suds to something like pysimplesoap

### ISSUE THREAD

**Issue by henrich** [psphere-project/psphere#21]
As reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=788086 ,
 suds is not maintained for long time since, so will be removed from Debian
 in next release. Then, psphere package will also be removed.

 Bug reported suggests replace subs with other implementation. For example,
 pysimplesoap is maintained and python3 ready.

 Could you consider to move it from depending suds?

**Comment by jkinred** [comment]
@henrich - Yes I will review pysimplesoap and determine if a move is possible. Thanks for the heads up!

**Comment by henrich** [comment]
:-)
